feat: add high level TableUtils interface.
priceloop/priceloop-api-python pull request #208
Opened 2023-12-04 10:51 UTC by djobyte

add Table and TableUtils Interface POC for high-level interaction with priceloop nocode platform.

2023-12-04 16:26 UTC, datitran commented on priceloop_api/priceloop/extras/table.py
> +    "datetime64[ns]": "date",
should this not be datetime on nocode side as well?

2023-12-05 11:50 UTC, GRBurst requested changes
If I understand correctly, this is just the first draft of adding some utils here.
However, there are many little things we can and should improve.

I am generally missing a concept to achieve a convenience and safe usage of those extras.
For example we still have to write the `workspace_name` and `table_name` in every function in utils (we could just provide them a table instead).
For added safety we **could** enforce keyword-only arguments on the functions if there are multiple parameters of the same type.
This could be covered by some documentation as well.

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/extras/exceptions.py
> +    pass
Exception classes should have an Error suffix according to pep 8, see https://peps.python.org/pep-0008/#exception-names

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/extras/__init__.py
> +from .helpers import get_priceloop_client
not sure if `get_priceloop_client` should be part of the __init__ here, for the reasons we talked about in tech discussion.

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/test/test_table.py
> +        assert True
what is the purpose of all the `assert True` here. If the function fail, the test fails as well.

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/test/test_table.py
> +            assert False
do you want to let if fail? There is e.g. `pytest.fail("Failed for some reason")`

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/test/test_table.py
> +            assert True
there is `pytest.raises():` to check for a raised error

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/test/test_table.py
could we add some type annotations here as well please :-)

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/extras/table.py
> +LIMIT = 30000  # cells
let's name it `CELL_LIMIT`, so it is also clear when using it

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/extras/table.py
> +COLUMNS_TYPES_MAPPING = {
should we name it consistent with line 65 so something like `PANDAS_TO_PLATFORM_MAPPING`?

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/extras/table.py
> +    Update = "update"
nice. Can we put those in model files, so we don't blow up this already big table.py file?

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/extras/table.py
> +class Column:
put in separate column.py module

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/extras/table.py
> +class TableUtils:
I'd say we put it in an extra module as well and use the newer `@define` attrs api

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/extras/table.py
> +        if pd.api.types.is_datetime64_any_dtype(df[column_name]):
I think nocode has datetime now

2023-12-05 11:50 UTC, GRBurst commented on priceloop_api/priceloop/extras/table.py
> +from retry import retry
In one tech discussion we talked about replacing retry, because it is not really maintained anymore (last update about 8 years ago) and quite limited

2023-12-05 12:06 UTC, datitran commented
The most important thing is also to add a README with examples on how to use it

2023-12-05 14:38 UTC, djobyte commented on priceloop_api/priceloop/extras/helpers.py
> +    return crededentials["token"]["access_token"]
this credentials file is meant to be used in the CI, it would have long-living credentials to test agains "local environment" of nocode.

2023-12-21 06:34 UTC, closed without merging